name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  umiuni2d_sprite:
    path: ../../umiuni2d_sprite
  umiuni2d_sprite_flutter:
    path: ../../umiuni2d_sprite_flutter
  umiuni2d_sprite_html5:
    path: ../../umiuni2d_sprite_html5
flutter:
  uses-material-design: true
  assets:
    - web/assets/chara.png

