name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  umiuni2d_sprite:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite.git
      ref: v0.0.5
  umiuni2d_sprite_flutter:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite_flutter.git
      ref: v0.0.5
  umiuni2d_sprite_html5:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite_html5.git
      ref: v0.0.5
flutter:
  uses-material-design: true
  assets:
    - web/assets/bg_clear01.png
    - web/assets/bg_clear02.png
    - web/assets/bg_clear03.png
    - web/assets/bg_clear04.png
    - web/assets/bg_clear05.png
    - web/assets/bg_clear06.png
